stages:
  - invoke


invoke:
  stage: invoke
  script:
    - sh ./start_test.sh test-plan-flux.jmx $TARGET_HOST $TARGET_PATH $TARGET_PORT $TARGET_PROTOCOL $TARGET_LOOPS $THREADS $influxdbUrl 
  tags:
    - public